window.WHYNOT_QUESTIONS=[
['💋','rel','Kiss them?','Поцеловать его или её?','Să-l sau s-o sărut?'],
['🔥','rel','Sleep with them?','Переспать с ним или с ней?','Să mă culc cu el sau cu ea?'],
['💬','rel','Text my ex?','Написать бывшему?','Să-i scriu fostului sau fostei?'],
['❤️','rel','Go on the date?','Идти на свидание?','Să merg la întâlnire?'],
['🌙','rel','Stay the night?','Остаться на ночь?','Să rămân peste noapte?'],
['🔁','rel','Give them another chance?','Дать ещё один шанс?','Să-i mai dau o șansă?'],
['💍','rel','Move in together?','Съезжаться вместе?','Să ne mutăm împreună?'],
['📵','rel','Stop texting first?','Перестать писать первым?','Să nu mai scriu eu primul?'],
['🫣','rel','Confess my feelings?','Признаться в своих чувствах?','Să-mi mărturisesc sentimentele?'],
['🚪','rel','End this relationship?','Закончить эти отношения?','Să închei relația asta?'],
['👀','rel','Check their phone?','Залезть в его или её телефон?','Să-i verific telefonul?'],
['😈','rel','Text the person I absolutely should not text?','Написать тому, кому точно не стоит писать?','Să-i scriu persoanei căreia clar nu ar trebui?'],
['💼','work','Quit my job?','Уволиться?','Să-mi dau demisia?'],
['😴','work','Skip work today?','Прогулять работу сегодня?','Să chiulesc azi de la muncă?'],
['📨','work','Send that email?','Отправить это письмо?','Să trimit acel e-mail?'],
['🙋','work','Ask for a raise?','Попросить прибавку?','Să cer o mărire?'],
['🚀','work','Start my own project?','Запустить свой проект?','Să-mi lansez propriul proiect?'],
['🗣️','work','Tell my boss what I really think?','Сказать начальнику, что я на самом деле думаю?','Să-i spun șefului ce cred cu adevărat?'],
['🏠','work','Work from home today?','Сегодня поработать из дома?','Să lucrez azi de acasă?'],
['🤝','work','Accept this offer?','Принять это предложение?','Să accept oferta asta?'],
['📚','work','Take another course?','Пойти ещё на один курс?','Să mai fac un curs?'],
['🧳','work','Change careers completely?','Полностью сменить профессию?','Să-mi schimb complet cariera?'],
['🧘','work','Do the bare minimum today?','Сегодня сделать только необходимый минимум?','Să fac azi doar strictul necesar?'],
['🔥','work','Send the resignation letter right now?','Отправить заявление об увольнении прямо сейчас?','Să trimit demisia chiar acum?'],
['🛍️','money','Buy this thing?','Купить эту вещь?','Să cumpăr asta?'],
['⌚','money','Buy another watch?','Купить ещё одни часы?','Să mai cumpăr un ceas?'],
['💸','money','Spend the money?','Потратить эти деньги?','Să cheltui banii?'],
['📱','money','Upgrade my phone?','Купить новый телефон?','Să-mi schimb telefonul?'],
['🎁','money','Buy myself a present for no reason?','Купить себе подарок без повода?','Să-mi cumpăr un cadou fără motiv?'],
['🧾','money','Cancel this subscription?','Отменить эту подписку?','Să anulez abonamentul?'],
['💳','money','Put it on the credit card?','Купить это в кредит?','Să plătesc cu cardul de credit?'],
['🏷️','money','Buy it just because it is on sale?','Купить только потому, что скидка?','Să cumpăr doar pentru că e la reducere?'],
['🍾','money','Splurge tonight?','Сегодня шикануть?','Să mă răsfăț serios în seara asta?'],
['💰','money','Lend them money?','Одолжить ему или ей деньги?','Să-i împrumut bani?'],
['🎰','money','Make one ridiculous impulse purchase?','Сделать одну совершенно безумную покупку?','Să fac o cumpărătură complet impulsivă?'],
['🫠','money','Pretend I did not see my bank balance?','Сделать вид, что я не видел баланс на карте?','Să mă prefac că nu am văzut soldul contului?'],
['✈️','travel','Book the flight?','Покупать билет?','Să cumpăr biletul?'],
['🧳','travel','Take another trip?','Поехать ещё в одно путешествие?','Să mai plec într-o călătorie?'],
['🌍','travel','Move abroad?','Переехать в другую страну?','Să mă mut în altă țară?'],
['🏖️','travel','Take a spontaneous weekend away?','Сорваться куда-нибудь на выходные?','Să plec spontan în weekend?'],
['🎒','travel','Travel alone?','Поехать одному или одной?','Să călătoresc singur?'],
['🗺️','travel','Go somewhere I know nothing about?','Поехать туда, о чём я почти ничего не знаю?','Să merg undeva despre care nu știu aproape nimic?'],
['🚆','travel','Change the route at the last minute?','Поменять маршрут в последний момент?','Să schimb traseul în ultimul moment?'],
['🏨','travel','Book the nicer hotel?','Взять отель подороже?','Să rezerv hotelul mai bun?'],
['🌅','travel','Wake up at 5 AM for that view?','Встать в пять утра ради этого вида?','Să mă trezesc la 5 pentru priveliștea asta?'],
['🧭','travel','Skip the plan and just wander?','Забить на план и просто гулять куда глаза глядят?','Să uit de plan și să mă plimb fără țintă?'],
['🛫','travel','Fly tomorrow just because the ticket is cheap?','Улететь завтра только потому, что билет дешёвый?','Să zbor mâine doar pentru că biletul e ieftin?'],
['🌴','travel','Extend the trip by three more days?','Продлить путешествие ещё на три дня?','Să prelungesc călătoria cu încă trei zile?'],
['🍷','life','Can I drink wine today?','Можно ли сегодня пить вино?','Pot să beau vin azi?'],
['🍰','life','Order another dessert?','Заказать ещё десерт?','Să mai comand un desert?'],
['🛋️','life','Do nothing today?','Можно сегодня ничего не делать?','Pot să nu fac nimic azi?'],
['🎉','life','Go to that party?','Идти на эту вечеринку?','Să merg la petrecere?'],
['📺','life','Watch one more episode?','Смотреть ещё одну серию?','Să mai văd un episod?'],
['🐈','life','Get a cat?','Завести кота?','Să iau o pisică?'],
['🍕','life','Order pizza?','Заказать пиццу?','Să comand pizza?'],
['🎤','life','Sing karaoke?','Пойти петь караоке?','Să merg la karaoke?'],
['📸','life','Post that photo?','Выложить эту фотографию?','Să postez fotografia?'],
['🧠','life','Stop overthinking it?','Перестать уже это обдумывать?','Să nu mă mai gândesc atât?'],
['💇','life','Change my hair dramatically?','Радикально сменить причёску?','Să-mi schimb radical coafura?'],
['🕺','life','Go dancing instead of being responsible?','Пойти танцевать вместо того, чтобы быть ответственным взрослым?','Să merg la dans în loc să fiu un adult responsabil?']
];